language: c

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: i586-mingw32msvc-gcc

script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)
